version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/meu_banco

  init_db:
    build: .
    command: python init_collections.py
    depends_on:
      - mongodb
    restart: "no"

volumes:
  mongo_data:
